version: "3"
services:

    mongo:
        image: mvertes/alpine-mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db
        environment:
            MONGODB_PASS: password
        command: "mongod --auth"

    mysql:
        image: k0st/alpine-mariadb
        ports: 
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: boilerroom
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
        command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"

    api:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        links:
            - mysql
            - mongo
            - redis
        ports:
            - "4000:4000"
        volumes:
            - ..:/boilerroom-server
        env_file:
            - .env
        command: "modd -f docker/modd/gunicorn.conf"

    celery:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        links:
            - mysql
            - mongo
            - redis
        volumes:
            - ..:/boilerroom-server
        env_file:
            - .env
        command: "modd -f docker/modd/celery.conf"

    flower:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        depends_on:
          - celery
        links:
            - redis
        ports:
            - "5555:5555"
        volumes:
            - ..:/boilerroom-server
        env_file:
            - .env
        command: "modd -f docker/modd/flower.conf"

volumes:
    mongo:
    mysql:
    redis:
